name: decorator_gen
version: 0.5.0
description: >-
  Automatically generates code for the decorator pattern in Dart by annotating classes.
repository: https://github.com/kcrpslcn/decorator_gen
environment:
  sdk: ^3.0.0

topics:
  - build-runner
  - codegen
  - decorator
  - design-pattern

dependencies:
  analyzer: ^8.0.0
  build: ^4.0.0
  decorator_annotation: ^0.3.0
  source_gen: ^4.0.0

dev_dependencies:
  build_runner: ^2.8.0
  source_gen_test: ^1.3.0
  test: ^1.26.2
