name: decorator_gen
version: 0.2.0
description: >-
  Automatically generates code for the decorator pattern in Dart by annotating
  Dart classes.
repository: https://github.com/kcrpslcn/decorator_gen
environment:
  sdk: ^3.0.0

topics:
  - build-runner
  - codegen

dependencies:
  analyzer: ^7.4.0
  build: ^3.0.0
  decorator_annotation: ^0.1.0
  source_gen: ^3.0.0

dev_dependencies:
  build_runner: ^2.6.0
  source_gen_test: ^1.3.0
  test: ^1.25.8
