name: decorator_gen
version: 0.1.1
description: >-
  Automatically generates code for the decorator pattern in Dart by annotating
  Dart classes.
repository: https://github.com/kcrpslcn/decorator_gen
environment:
  sdk: ^3.0.0

topics:
  - build-runner
  - codegen

dependencies:
  analyzer: ^7.5.5
  build: ^2.5.4
  decorator_annotation: ^0.1.0
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.5.4
  source_gen_test: ^1.1.2
  test: ^1.25.8
  yaml: ^3.1.2
